// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY3BGU71CNgHT2Hll6nQzRfIf2fiqvc_U',
    appId: '1:1091448795452:web:a2c317ecd94de6a3d8ee39',
    messagingSenderId: '1091448795452',
    projectId: 'car-rental-app-1790f',
    authDomain: 'car-rental-app-1790f.firebaseapp.com',
    storageBucket: 'car-rental-app-1790f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA33HoGsQcTAs7YeSrw0Bys6NxXp8WYl0M',
    appId: '1:1091448795452:android:34e9768f79949327d8ee39',
    messagingSenderId: '1091448795452',
    projectId: 'car-rental-app-1790f',
    storageBucket: 'car-rental-app-1790f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvHDJdSYcKKTo6P1n_8A4-6z8Y65ZrFjU',
    appId: '1:1091448795452:ios:4c98ff70b8a05ab8d8ee39',
    messagingSenderId: '1091448795452',
    projectId: 'car-rental-app-1790f',
    storageBucket: 'car-rental-app-1790f.appspot.com',
    iosClientId: '1091448795452-5v59kdf6c6d9rh5e22fvlgqepf5g5jfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.carApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvHDJdSYcKKTo6P1n_8A4-6z8Y65ZrFjU',
    appId: '1:1091448795452:ios:4c98ff70b8a05ab8d8ee39',
    messagingSenderId: '1091448795452',
    projectId: 'car-rental-app-1790f',
    storageBucket: 'car-rental-app-1790f.appspot.com',
    iosClientId: '1091448795452-5v59kdf6c6d9rh5e22fvlgqepf5g5jfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.carApp',
  );
}
